# Generated by Django 2.0 on 2017-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='residencia',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
