# Generated by Django 2.0 on 2017-12-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krato', '0003_auto_20171216_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tiendas',
            field=models.ManyToManyField(related_name='usuarios', to='krato.Tienda'),
        ),
    ]
